### Get all persons
GET http://localhost:3001/api/persons

### Delete a person
DELETE http://localhost:3001/api/persons/947450

### Create a new person
POST http://localhost:3001/api/persons
Content-type: application/json

{
  "name": "yes",
  "number": "123456789"
}

### Get all persons again
GET http://localhost:3001/api/persons
