### Get all persons
GET https://phonebook-b.onrender.com/api/persons

### Delete a person
DELETE https://phonebook-b.onrender.com/api/persons/947450

### Create a new person
POST https://phonebook-b.onrender.com/api/persons
Content-type: application/json

{
  "name": "yes",
  "number": "123456789"
}

### Get all persons
GET https://phonebook-b.onrender.com/api/persons
